import { app, BrowserWindow } from 'electron';
import { ipcMain } from 'electron';
import { DeleteRowFromDatabaseProps, GetDbLocalPathProps, OnDeleteRowFromDatabaseResult, OnGetDbLocalPathResult, OnReadDatabaseRowsResult, OnWriteRowToDatabaseResult, ReadDatabaseRowsProps, WriteRowToDatabaseProps } from './preload';
import { FinanceSheetRow, WesterhamDatabase, WesterhamDatabaseEnum } from './db/WesterhamDatabase';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const defaultDb = `${app.getPath("userData")}\\${WesterhamDatabaseEnum.MATTHEW}`;
let db = new WesterhamDatabase(defaultDb);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1200,
    width: 1600,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
ipcMain.on('readDatabaseRows', async (event, props: ReadDatabaseRowsProps) => {
  const rows: FinanceSheetRow[] = await db.getAllFinanceSheetRows();
  const response: OnReadDatabaseRowsResult = {
    rows 
  };
  event.reply('readDatabaseRowsResult', response);
});
ipcMain.on('writeRowToDatabase', async (event, props: WriteRowToDatabaseProps) => {

  db.insertFinanceSheetRow(props.row);

  const response: OnWriteRowToDatabaseResult = {
    data: props.row
  };

  event.reply('writeRowToDatabaseResult', response);
});
ipcMain.on('deleteRowFromDatabase', async (event, props: DeleteRowFromDatabaseProps) => {

  await db.deleteFinanceSheetRow(props.transactionId);

  const response: OnDeleteRowFromDatabaseResult = {
    data: `Deleted transactionId (${props.transactionId})`
  };

  event.reply('deleteRowFromDatabaseResult', response);
});
ipcMain.on('getDbLocalPath', async (event, props: GetDbLocalPathProps) => {
  const response: OnGetDbLocalPathResult = {
    path: db.getDbPath()
  };
  event.reply('getDbLocalPathResult', response);
});