import { app, BrowserWindow, shell } from 'electron';
import { updateElectronApp } from 'update-electron-app';
import { ipcMain } from 'electron';
import { AttachDatabaseProps, DeleteDatabaseRulesProps, DeleteRowFromDatabaseProps, GetAllExistingDatabasesProps, GetDbLocalPathProps, GetDistinctValuesOfColumnProps, OnAttachDatabaseResult, OnDeleteDatabaseRulesResult, OnDeleteRowFromDatabaseResult, OnGetAllExistingDatabasesResult, OnGetDbLocalPathResult, OnGetDistinctValuesOfColumnResult, OnReadDatabaseRowsResult, OnReadDatabaseRulesResult, OnReadEmptyCategoryDatabaseRowsResult, OnUpdateRowInDatabaseResult, OnUpdateRuleInDatabaseResult, OnWriteDatabaseRulesResult, OnWriteRowToDatabaseIfMissingResult, OnWriteRowToDatabaseResult, ReadDatabaseRowsProps, ReadDatabaseRulesProps, ReadEmptyCategoryDatabaseRowsProps, UpdateRowInDatabaseProps, UpdateRuleInDatabaseProps, WriteDatabaseRulesProps, WriteRowToDatabaseIfMissingProps, WriteRowToDatabaseProps, ReadFileTypesProps, OnReadFileTypesResult, WriteFileTypeProps, OnWriteFileTypeResult, DeleteFileTypeProps, OnDeleteFileTypeResult, UpdateFileTypeProps, OnUpdateFileTypeResult, OpenDbDirectoryProps, OnOpenDbDirectoryResult, OpenBackupsDirectoryProps, OnOpenBackupsDirectoryResult } from './preload';
import { DatabaseName, FinanceSheetRow, WesterhamDatabase } from './db/WesterhamDatabase';
import path from 'path';
import { FileService } from './file/FileService';
import { BackupService } from './file/BackupService';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Enable autoupdates
updateElectronApp({
  updateInterval: "5 minutes",
});

const dbsTargetPath = path.join(app.getPath("userData"), 'financeApp', 'dbs');
let db = new WesterhamDatabase(FileService.getOrCreateDbFilePath(dbsTargetPath, DatabaseName.DEFAULT));
BackupService.backup(db.getDbPath());
db.ensureFileTypesTable();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1200,
    width: 1600,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.on('getAllExistingDatabases', async (event, props: GetAllExistingDatabasesProps) => {
  const fileNames: string[] = FileService.getFilenamesInDirectory(dbsTargetPath);
  const response: OnGetAllExistingDatabasesResult = {
    databases: fileNames 
  };
  event.reply('getAllExistingDatabases', response);
});

ipcMain.on('attachDatabase', async (event, props: AttachDatabaseProps) => {
  db = new WesterhamDatabase(FileService.getOrCreateDbFilePath(dbsTargetPath, props.databaseName));
  BackupService.backup(db.getDbPath());
  db.ensureFileTypesTable();
  const response: OnAttachDatabaseResult = {
    success: true, 
  };
  event.reply('attachDatabase', response);
});

ipcMain.on('readDatabaseRows', async (event, props: ReadDatabaseRowsProps) => {
  const rows: FinanceSheetRow[] = await db.getAllFinanceSheetRows();
  const response: OnReadDatabaseRowsResult = {
    rows 
  };
  event.reply('readDatabaseRowsResult', response);
});
ipcMain.on('writeRowToDatabase', async (event, props: WriteRowToDatabaseProps) => {
  const originalLastId = await db.getLastTransactionId();
  await db.insertFinanceSheetRow(props.row);
  BackupService.backup(db.getDbPath());
  const newLastId = await db.getLastTransactionId();

  const response: OnWriteRowToDatabaseResult = {
    data: props.row,
    newTransactionId: newLastId
  };

  event.reply('writeRowToDatabaseResult', response);
});
ipcMain.on('deleteRowFromDatabase', async (event, props: DeleteRowFromDatabaseProps) => {

  await db.deleteFinanceSheetRow(props.transactionId);
  BackupService.backup(db.getDbPath());

  const response: OnDeleteRowFromDatabaseResult = {
    deletedId: props.transactionId,
    deleted: true,
  };

  event.reply('deleteRowFromDatabaseResult', response);
});
ipcMain.on('readEmptyCategoryDatabaseRows', async (event, props: ReadEmptyCategoryDatabaseRowsProps) => {
  const rows: FinanceSheetRow[] = await db.getAllFinanceSheetRowsWhereColumnEmpty("category");
  const response: OnReadEmptyCategoryDatabaseRowsResult = {
    rows 
  };
  event.reply('readEmptyCategoryDatabaseRowsResult', response);
});
ipcMain.on('writeRowToDatabaseIfMissing', async (event, props: WriteRowToDatabaseIfMissingProps) => {
  const originalLastId = await db.getLastTransactionId();
  const duplicateMap: Record<string, boolean> = {}; // To store duplicates
  const nonExistingRows: FinanceSheetRow[] = [];

  for (const row of props.rows) {
    const exists = await db.checkIfRowExists(row);
    duplicateMap[JSON.stringify(row)] = exists; // Store whether the row exists

    if (!exists) {
      nonExistingRows.push(row);
    }
  }

  // Insert only the non-existing rows
  const insertPromises = nonExistingRows.map(row => {
    return new Promise<void>(async (resolve, reject) => {
      await db.insertFinanceSheetRow(row);
      resolve();
    });
  });

  await Promise.all(insertPromises);
  
  if (nonExistingRows.length > 0) {
    BackupService.backup(db.getDbPath());
  }
  
  const newLastId = await db.getLastTransactionId();

  const response: OnWriteRowToDatabaseIfMissingResult = {
    requestedRowCount: props.rows.length,
    writtenRowCount: nonExistingRows.length,
    oldLastTransactionId: originalLastId,
    newLastTransactionId: newLastId,
  };

  event.reply('writeRowToDatabaseIfMissingResult', response);
});

ipcMain.on('getDbLocalPath', async (event, props: GetDbLocalPathProps) => {
  const response: OnGetDbLocalPathResult = {
    path: db.getDbPath()
  };
  event.reply('getDbLocalPathResult', response);
});

ipcMain.on('updateRowInDatabase', async (event, props: UpdateRowInDatabaseProps) => {

  db.updateFinanceSheetRow(props.transactionId, props.row);
  BackupService.backup(db.getDbPath());

  const response: OnUpdateRowInDatabaseResult = {
    data: props.row
  };
  event.reply('onUpdateRowInDatabase', response);
});

// Read all rules
ipcMain.on('readDatabaseRules', async (event, props: ReadDatabaseRulesProps) => {
  try {
    const rules = await db.getAllRules();
    const response: OnReadDatabaseRulesResult = { rules };
    event.reply('readDatabaseRulesResult', response);
  } catch (err) {
    console.error("Error reading rules:", err);
    event.reply('readDatabaseRulesResult', { rules: [] }); // fallback
  }
});

// Write a new rule
ipcMain.on('writeDatabaseRules', async (event, props: WriteDatabaseRulesProps) => {
  try {
    const insertPromises = props.rules.map(rule => {
      return new Promise<void>(async (resolve, reject) => {
        await db.insertRule(rule);
        resolve();
      });
    });

    await Promise.all(insertPromises);
    BackupService.backup(db.getDbPath());

    const response: OnWriteDatabaseRulesResult = {
      data: props.rules,
    };
    event.reply('writeDatabaseRulesResult', response);
  } catch (err) {
    console.error("Error writing rule:", err);
    const response: OnWriteDatabaseRulesResult = {
      data: props.rules,
      err,
    };
    event.reply('writeDatabaseRulesResult', response);
  }
});

// Delete a rule
ipcMain.on('deleteDatabaseRules', async (event, props: DeleteDatabaseRulesProps) => {
  try {
    await db.deleteRule(props.ruleId);
    BackupService.backup(db.getDbPath());
    const response: OnDeleteDatabaseRulesResult = { deletedId: props.ruleId, deleted: true };
    event.reply('deleteDatabaseRulesResult', response);
  } catch (err) {
    console.error("Error deleting rule:", err);
    const response: OnDeleteDatabaseRulesResult = { deletedId: props.ruleId, deleted: false, err };
    event.reply('deleteDatabaseRulesResult', response);
  }
});

ipcMain.on('updateRuleInDatabase', async (event, props: UpdateRuleInDatabaseProps) => {
  db.updateRuleRow(props.ruleId, props.rule);
  BackupService.backup(db.getDbPath());

  const response: OnUpdateRuleInDatabaseResult = {
    data: props.rule
  };
  event.reply('onUpdateRuleInDatabase', response);
});

ipcMain.on('getDistinctValuesOfColumn', async (event, props: GetDistinctValuesOfColumnProps) => {
  const values: string[] = await db.getDistinctColumnValues(props.table, props.column);

  const response: OnGetDistinctValuesOfColumnResult = {
    distinctValues: values
  };
  event.reply('onGetDistinctValuesOfColumn', response);
});

// ─── File Types ───────────────────────────────────────────────────────────────

ipcMain.on('readFileTypes', async (event, props: ReadFileTypesProps) => {
  try {
    const fileTypes = await db.getAllFileTypes();
    const response: OnReadFileTypesResult = { fileTypes };
    event.reply('readFileTypesResult', response);
  } catch (err) {
    console.error("Error reading file types:", err);
    event.reply('readFileTypesResult', { fileTypes: [] });
  }
});

ipcMain.on('writeFileType', async (event, props: WriteFileTypeProps) => {
  try {
    await db.insertFileType(props.fileType);
    BackupService.backup(db.getDbPath());
    const response: OnWriteFileTypeResult = { data: props.fileType };
    event.reply('writeFileTypeResult', response);
  } catch (err) {
    console.error("Error writing file type:", err);
    event.reply('writeFileTypeResult', { data: null, err });
  }
});

ipcMain.on('deleteFileType', async (event, props: DeleteFileTypeProps) => {
  try {
    await db.deleteFileType(props.fileTypeId);
    BackupService.backup(db.getDbPath());
    const response: OnDeleteFileTypeResult = { deletedId: props.fileTypeId, deleted: true };
    event.reply('deleteFileTypeResult', response);
  } catch (err) {
    console.error("Error deleting file type:", err);
    event.reply('deleteFileTypeResult', { deletedId: props.fileTypeId, deleted: false, err });
  }
});

ipcMain.on('updateFileType', async (event, props: UpdateFileTypeProps) => {
  try {
    await db.updateFileTypeRow(props.fileTypeId, props.fileType);
    BackupService.backup(db.getDbPath());
    const response: OnUpdateFileTypeResult = { data: props.fileType };
    event.reply('updateFileTypeResult', response);
  } catch (err) {
    console.error("Error updating file type:", err);
    event.reply('updateFileTypeResult', { data: null, err });
  }
});

ipcMain.on('openDbDirectory', async (event, props: OpenDbDirectoryProps) => {
  shell.openPath(dbsTargetPath);
  const response: OnOpenDbDirectoryResult = { success: true };
  event.reply('openDbDirectoryResult', response);
});

const backupsTargetPath = path.join(app.getPath("userData"), 'financeApp', 'backups', 'dbs');

ipcMain.on('openBackupsDirectory', async (event, props: OpenBackupsDirectoryProps) => {
  shell.openPath(backupsTargetPath);
  const response: OnOpenBackupsDirectoryResult = { success: true };
  event.reply('openBackupsDirectoryResult', response);
});
